USE PET_DB;
CREATE TABLE `user` (
    `USER_NO` INT NOT NULL AUTO_INCREMENT,
    `USER_NAME` VARCHAR(10) NOT NULL,
    `NICKNAME` VARCHAR(10) NOT NULL,
    `USER_PHONE` VARCHAR(15) NOT NULL,
    `EMAIL` VARCHAR(100) NOT NULL,
    `PASSWORD` VARCHAR(100) NOT NULL,
    `USER_TAYPE` INT NOT NULL,
    `BUSINESS_REGISTRATION` INT NULL,
    `JOINED_DATE` DATE NOT NULL,
    CONSTRAINT PK_USER_NO PRIMARY KEY (USER_NO)
);

INSERT INTO `user` (`USER_NO`, `USER_NAME`, `NICKNAME`, `USER_PHONE`, `EMAIL`, `PASSWORD`, `USER_TAYPE`, `BUSINESS_REGISTRATION`, `JOINED_DATE`)
VALUES (1, '김길동', '길동', '01011111111', 'SDF@NAVER.COM', '111', 1, NULL ,'2024-03-27');
 
